version: "3.9"

services:
  
  front:
    build: ./front
    volumes:
      - ./front/src:/code/src
    ports:
      - "3000:3000"
    depends_on:
      - api
  
  api:
    build: ./back/back
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
     - ./back/back:/code
    ports:
     - "5000:8000"
    env_file:
      - ./back/.env
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.2.0
    # quiet
    command: elasticsearch -q
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_data_tacs:/usr/share/elasticsearch/data

volumes:
  elasticsearch_data_tacs:
