version: "3.9"

services:
  db:
    image: mongo:4.4.6
    command: mongod --quiet --logpath /dev/null
    volumes:
      - tacs-mongo-data:/data/db
    env_file:
      - ./back/envs/.env
    ports:
      - "27017:27017"

  front:
    build: ./front
    volumes:
      - ./front/src:/code/src
    ports:
      - "3000:3000"
    depends_on:
      - back
     

  back:
    build:
      context: ./back/api
      dockerfile: Dockerfile
    tty: true
    env_file:
      - ./back/envs/.env
    volumes:
      - ./back/api:/code
    command: python3 app.py
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  tacs-mongo-data:



  